const btnDefault = {
  border: "none",
  textTransform: "none",
};
const descpColor = "#666666";

export const network = {
  parentCont: { bgcolor: "#F4F2EE", height: "100vh" },
  mainCont: { py: 2, display: "flex", aligItems: "center", gap: 2 },
  manageCont: {
    mainCont: {
      backgroundColor: "white",
      width: { lg: "40%", md: "50%", sm: "60%" },
      borderRadius: "8px",
      border: "1px groove  #e1e1e1",
      display: { sm: "block", xs: "none" },
      height: "fit-content  ",
    },
    manageCont: {
      py: 1.4,
      px: 1,
      display: "flex",
      flexDirection: "column",
    },
    manageText: {
      pl: 1,
      fontFamily: "Montserrat, sans-serif",
      fontWeight: 550,
      color: "black",
      whiteSpace: "nowrap",
    },
    fieldCont: {
      display: "flex",
      alignItems: "center",
      gap: 2,
      py: 1,
      pl: 1.8,
      "&:hover": { cursor: "pointer", bgcolor: "#EBEBEB" },
    },
    showMoreBtn: {
      ...btnDefault,
      color: descpColor,
      fontWeight: 550,
      px: 0,
      width: "120px",
      "&:hover": {
        backgroundColor: "#EBEBEB",
        border: "none",
      },
    },
    divider: { borderColor: "#e1e1e1", mt: 1, mb: 1 },
    icons: { color: descpColor },
    text: { color: descpColor, whiteSpace: "nowrap" },
    advImgCont: { width: "100%" },
    advImg: { width: "100%" },
    displayNetwork: {
      height: "250px",
      transition: "height 0.2s ease-out",
    },
    hideDisplayNetwork: {
      height: "0px",
      overflow: "hidden",
      transition: "height 0.2s ease-in",
    },
    footerCont: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "column",
      py: 2,
    },
    footerText: {
      color: descpColor,
      fontSize: 12,
      "&:hover": { color: "#1976d2", textDecoration: "underline" },
    },
    footerList: {
      display: "flex",
      flexWrap: "wrap",
      gap: 1,
      alignItems: "center",
      justifyContent: "center",
      px: 7,
      py: 1,
    },
    footerImg: { width: "50px" },
    copyrightCont: {
      display: "flex",
      alignItems: "center",
      flexWrap: "wrap",
      px: 4,
      gap: 1,
      justifyContent: "center",
    },
    copyrightText: { fontSize: 12 },
  },
  cardsCont: {
    mainCont: {
      display: { xs: "flex" },
      flexDirection: "column",
      gap: 2,
      width: { xs: "100%" },
    },
    pendingCont: {
      bgcolor: "white",
      borderRadius: "8px",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      px: 2,
      py: 1.5,
      border: "1px groove  #e1e1e1",
    },
    cardsCont: {
      border: "1px groove  #e1e1e1",
      display: "flex",
      flexDirection: "column",
      px: 2,
      py: 2,
      bgcolor: "white",
      borderRadius: "8px",
    },
    titleCont: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
    },
    peoplesList: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      flexWrap: "wrap",
      gap: 1,
      mt: 1.5,
    },
    peoplesPaper: {
      width: { lg: "250px", md: "290px" },
      height: { md: "270px", sm: "300px", xs: "270px" },
      borderRadius: "8px",
      overflow: "hidden",
      border: "1px groove  #e1e1e1",
    },
    peopleImagesCont: { position: "relative" },
    closeIcon: {
      position: "absolute",
      right: 8,
      backgroundColor: "black",
      color: "white",
      borderRadius: "50px",
      opacity: 0.7,
      top: 15,
      cursor: "pointer",
    },
    peopleBgImgCont: { width: "100%" },
    peopleBgImg: { width: "100%" },
    peopleProfileImgCont: {
      width: "60px",
      borderRadius: "30px",
      position: "absolute",
      bottom: -20,
      left: 10,
    },
    peopleProfileImg: {
      width: "100%",
      borderRadius: "50px",
    },
    personDetailsCont: {
      mt: 3,
      px: 1,
      height: { md: "60%", sm: "50%", xs: "50%" },
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
    },
    personName: { fontWeight: 550 },
    personDesignation: { fontSize: 14, color: descpColor },
    personTalks: {
      fontSize: 13,
      color: descpColor,
    },
    personFollowers: {
      fontSize: 13,
      color: descpColor,
    },
    personBtnCont: { marginTop: "auto", width: "100%" },
    followBtn: {
      borderRadius: "30px",
      width: "100%",
      textTransform: "none",
      fontWeight: 700,
      "&:hover": { bgcolor: "#E0EFFF", border: "1px solid #4698EF" },
    },
    followedBtn: {
      borderRadius: "30px",
      width: "100%",
      textTransform: "none",
      fontWeight: 700,
      borderColor: "black",
      color: "#606060",
      "&:hover": { bgcolor: "#EBEBEB", border: "1px solid black" },
    },
  },
};

export const message = {
  mainCont: {
    position: "absolute",
    backgroundColor: "white",
    bottom: 0,
    right: 20,
    width: "300px",
    borderTopLeftRadius: "8px",
    borderTopRightRadius: "8px",

    border: "1px groove  #e1e1e1",
  },
  divider: {
    border: "0.2px slid  #e1e1e1",
  },
  accountimg: { width: "40px", borderRadius: "8px" },
  topTabIcons: { color: "#666666", fontSize: 25 },
  topTabEditIcons: { color: "#666666", fontSize: 15 },
  searchCont: {
    bgcolor: "#EDF3F8",
    display: "flex",
    alignItems: "center",
    py: 0.8,
    px: 0.5,
    borderRadius: 1,
  },
  inputField: { border: "none", bgcolor: "#EDF3F8", width: '100%', outline: 'none' },
  inputSearchIcon: {
    color: "#666666",
  },
  inputTuneIcon: {
    color: "#666666",
  },
};

export const navbar = {}